context:
  version: 1.7.2

package:
  name: curlie
  version: ${{ version }}

source:
  url: https://github.com/rs/curlie/archive/v${{ version }}.tar.gz
  sha256: b2ced685c6d2cde951cbd894ecc16df2f987f9d680830bcf482a7dcd22165116

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-cgo') }}
    - go-licenses
  host:
    - curl
    - libcurl

tests:
  - script:
      - curlie --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Power of curl, ease of use of httpie
  homepage: https://github.com/rs/curlie
  repository: https://github.com/rs/curlie

extra:
  recipe-maintainers:
    - danielnachun
