context:
  version: "1.8.1"

package:
  name: curlie
  version: ${{ version }}

source:
  url: https://github.com/rs/curlie/archive/v${{ version }}.tar.gz
  sha256: 0b90d359b94af1d32cb2d34607f2bee10200e2f6a35f55840472e78dab7ed6f4

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-cgo') }}
    - ${{ stdlib('c') }}
    - go-licenses
  host:
    - curl
    - libcurl

tests:
  - script:
      - curlie --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Power of curl, ease of use of httpie
  homepage: https://github.com/rs/curlie
  repository: https://github.com/rs/curlie

extra:
  recipe-maintainers:
    - danielnachun
